import com.android.build.api.dsl.ApplicationExtension
import de.aaschmid.gradle.plugins.cpd.Cpd
import io.gitlab.arturbosch.detekt.Detekt
import io.gitlab.arturbosch.detekt.extensions.DetektExtension
import kotlinx.kover.gradle.plugin.dsl.KoverProjectExtension

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.hilt) apply false
    alias(libs.plugins.room) apply false
    /**
     * Code checks. None of them runs during an ordinary build; they run
     * with `./gradlew qualityCheck` and write reports under build/reports.
     */
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.kover)
    alias(libs.plugins.dependency.analysis)
    alias(libs.plugins.cpd)
}

/** The one coverage report covers the JVM module and the debug build of each Android module. */
val coverageVariant = "anuj"

/** Modules that hold tests about the code rather than code of their own. */
val checkOnlyModules = setOf(":quality")

subprojects {
    /** `:core` and `:feature` are only folders; they have no code to check. */
    if (childProjects.isNotEmpty()) return@subprojects

    apply(plugin = "io.gitlab.arturbosch.detekt")
    extensions.configure<DetektExtension> {
        buildUponDefaultConfig = true
        config.setFrom(rootProject.file("config/detekt/detekt.yml"))
        baseline = rootProject.file("config/detekt/baseline-${project.path.trim(':').replace(':', '-')}.xml")
        basePath = rootProject.projectDir.absolutePath
        parallel = true
        /** A first report, not a gate: the findings are listed and the build carries on. */
        ignoreFailures = true
    }
    dependencies {
        "detektPlugins"(rootProject.libs.detekt.formatting)
    }
    /**
     * Detekt 1.23 carries its own Kotlin compiler (2.0.21). The build uses
     * Kotlin 2.1.20, and without this the newer version leaks into detekt's
     * classpath and it refuses to run.
     */
    configurations.matching { it.name == "detekt" }.configureEach {
        resolutionStrategy.eachDependency {
            if (requested.group == "org.jetbrains.kotlin") useVersion("2.0.21")
        }
    }
    tasks.withType<Detekt>().configureEach {
        jvmTarget = "17"
        reports {
            html.required.set(true)
            xml.required.set(false)
            txt.required.set(true)
            sarif.required.set(false)
            md.required.set(false)
        }
    }

    if (path !in checkOnlyModules) {
        apply(plugin = "org.jetbrains.kotlinx.kover")
        extensions.configure<KoverProjectExtension> {
            currentProject {
                createVariant(coverageVariant) {
                    add("jvm", "debug", optional = true)
                }
            }
        }
        rootProject.dependencies.add("kover", this)
        /** Each module reports its own unused or misplaced libraries; the root gathers them in buildHealth. */
        apply(plugin = "com.autonomousapps.dependency-analysis")
    }

    /** Android Lint is run once, from the app, and looks into every module the app uses. */
    pluginManager.withPlugin("com.android.application") {
        extensions.configure<ApplicationExtension> {
            lint {
                checkDependencies = true
                abortOnError = false
                htmlReport = true
                xmlReport = false
                textReport = false
                lintConfig = rootProject.file("config/lint/lint.xml")
            }
        }
    }
}

kover {
    currentProject {
        createVariant(coverageVariant) {}
    }
    reports {
        filters {
            excludes {
                /** Generated by Hilt, Room and Compose; nobody writes tests for these. */
                classes(
                    "*_Factory", "*_Factory\$*", "*_HiltModules*", "*_MembersInjector", "Hilt_*", "*_Impl", "*_Impl\$*",
                    "dagger.hilt.*", "hilt_aggregated_deps.*", "*ComposableSingletons*", "*.BuildConfig",
                )
            }
        }
    }
}

/** Copy-pasted code. Kotlin only; the limit is the number of tokens that must match before it counts. */
cpd {
    language = "kotlin"
    toolVersion = libs.versions.pmd.get()
    /** `-PcpdTokens=60` looks for shorter repeats than the usual 120. */
    minimumTokenCount = (findProperty("cpdTokens") as String?)?.toInt() ?: 120
    isIgnoreFailures = true
}
tasks.withType<Cpd>().configureEach {
    source = fileTree(rootDir) {
        include("**/src/main/kotlin/**/*.kt")
        exclude("**/build/**")
    }
    reports {
        text.required.set(true)
        xml.required.set(false)
    }
}

dependencyAnalysis {
    issues {
        all {
            onAny {
                severity("warn")
            }
        }
    }
}

/**
 * Every check in one go. Each one writes a report and none of them stops
 * the others; the Konsist tests in :quality are the only ones that fail the
 * run, because they are the project's own architecture rules.
 */
tasks.register("qualityCheck") {
    group = "verification"
    description = "Runs detekt, Android Lint, duplicate detection, the architecture tests, dependency advice and coverage."
    dependsOn(subprojects.filter { it.childProjects.isEmpty() }.map { "${it.path}:detekt" })
    dependsOn(":app:lintDebug", "cpdCheck", ":quality:test", "buildHealth", "koverHtmlReport${coverageVariant.replaceFirstChar(Char::uppercase)}")
}
